title: Site

pages: default

fields:
  title:
    label: Title
    type:  text

  author:
    label: Author
    type:  text

  email:
    label: Email
    type: text

  facebook:
    label: Facebook
    type: text
    width: 1/3

  twitter:
    label: Twitter
    type: text
    width: 1/3

  instagram:
    label: Instagram
    type: text
    width: 1/3

  description:
    label: Description
    type:  textarea
    
  copyright:
    label: Copyright
    type:  textarea

